[package]
name = "mentor-script"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
eframe = "0.33.3"
rodio = "0.21.1"
rand = "0.9.2"
reqwest = {  version = "0.13.1", features = ["blocking"] }